# Generated by Django 4.0.7 on 2023-03-02 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ORDR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CardCode', models.CharField(max_length=50)),
                ('DocDate', models.DateField()),
            ],
        ),
    ]
