# Generated by Django 4.0.7 on 2023-05-09 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ORDR', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ORDR',
        ),
    ]
