# Generated by Django 4.0.7 on 2022-09-22 02:36

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_firstname', models.CharField(max_length=200, verbose_name='First Name')),
                ('user_lastname', models.CharField(max_length=200, verbose_name='Last Name')),
                ('user_username', models.CharField(max_length=200, unique=True, verbose_name='User Name')),
                ('user_id', models.PositiveIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('user_email', models.EmailField(max_length=200, unique=True, verbose_name='Email')),
                ('user_createdate', models.DateField(default=datetime.datetime(2022, 9, 22, 2, 36, 8, 989530, tzinfo=utc))),
            ],
        ),
    ]
