# Generated by Django 4.0.7 on 2022-09-22 03:29

import OUSR.models
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('OUSR', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_profilepic',
            field=models.ImageField(default='profile_pic/image.jpg', upload_to=OUSR.models.image_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_createdate',
            field=models.DateField(default=datetime.datetime(2022, 9, 22, 3, 29, 56, 697824, tzinfo=utc)),
        ),
    ]
