# Generated by Django 4.0.7 on 2022-10-07 14:11

import OUSR.models
import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('OUSR', '0002_user_user_profilepic_alter_user_user_createdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_createdate',
            field=models.DateField(default=datetime.datetime(2022, 10, 7, 14, 11, 12, 828089, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_profilepic',
            field=models.ImageField(default='profile_pic/default.jpg', upload_to=OUSR.models.image_path),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sapb1_employee_id', models.PositiveIntegerField(unique=True, verbose_name='SAP B1 Employee ID')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='OUSR.user')),
            ],
        ),
    ]
