# Generated by Django 4.0.7 on 2022-10-08 02:38

import OUSR.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('OUSR', '0003_alter_user_user_createdate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_id',
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='user_createdate',
            field=models.DateField(default=datetime.datetime(2022, 10, 8, 2, 37, 41, 801443, tzinfo=utc), null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_email',
            field=models.EmailField(max_length=200, null=True, unique=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_profilepic',
            field=models.ImageField(default='profile_pic/default.jpg', null=True, upload_to=OUSR.models.image_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sapb1_employee_id',
            field=models.PositiveIntegerField(null=True, unique=True, verbose_name='SAP B1 Employee ID'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
