# Generated by Django 4.0.7 on 2022-10-08 02:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('OUSR', '0004_remove_profile_user_id_profile_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sapb1_employee_id',
            field=models.PositiveIntegerField(default=1, unique=True, verbose_name='SAP B1 Employee ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_createdate',
            field=models.DateField(default=datetime.datetime(2022, 10, 8, 2, 46, 51, 346702, tzinfo=utc), null=True),
        ),
    ]
