# Generated by Django 4.0.7 on 2022-10-08 03:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('OUSR', '0005_alter_profile_sapb1_employee_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_updatedate',
            field=models.DateField(default=datetime.datetime(2022, 10, 8, 3, 3, 10, 588130, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_createdate',
            field=models.DateField(default=datetime.datetime(2022, 10, 8, 3, 3, 10, 588130, tzinfo=utc), null=True),
        ),
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_createdate', models.DateField(default=datetime.datetime(2022, 10, 8, 3, 3, 10, 588130, tzinfo=utc), null=True)),
                ('user_updatedate', models.DateField(default=datetime.datetime(2022, 10, 8, 3, 3, 10, 588130, tzinfo=utc), null=True)),
                ('user_modules', models.TextField(verbose_name='Modules')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
