# Generated by Django 4.0.7 on 2022-10-08 04:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('OUSR', '0007_alter_modules_user_createdate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_email',
        ),
        migrations.AlterField(
            model_name='modules',
            name='user_createdate',
            field=models.DateField(default=datetime.datetime(2022, 10, 8, 4, 27, 29, 93150, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='modules',
            name='user_updatedate',
            field=models.DateField(default=datetime.datetime(2022, 10, 8, 4, 27, 29, 93150, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_createdate',
            field=models.DateField(default=datetime.datetime(2022, 10, 8, 4, 27, 29, 93150, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_updatedate',
            field=models.DateField(default=datetime.datetime(2022, 10, 8, 4, 27, 29, 93150, tzinfo=utc), null=True),
        ),
    ]
