# Generated by Django 4.0.7 on 2022-10-09 02:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('OUSR', '0009_profile_user_locked_profile_user_superuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_database',
            field=models.CharField(default='SBODemoAU', max_length=100, verbose_name='Database'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='modules',
            name='user_createdate',
            field=models.DateField(default=datetime.datetime(2022, 10, 9, 2, 2, 57, 454061, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='modules',
            name='user_updatedate',
            field=models.DateField(default=datetime.datetime(2022, 10, 9, 2, 2, 57, 454061, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_createdate',
            field=models.DateField(default=datetime.datetime(2022, 10, 9, 2, 2, 57, 454061, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_updatedate',
            field=models.DateField(default=datetime.datetime(2022, 10, 9, 2, 2, 57, 454061, tzinfo=utc), null=True),
        ),
    ]
