# Generated by Django 4.0.7 on 2022-10-09 02:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('OUSR', '0011_alter_modules_user_createdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modules',
            name='user_createdate',
            field=models.DateField(default=datetime.datetime(2022, 10, 9, 2, 30, 20, 625685, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='modules',
            name='user_updatedate',
            field=models.DateField(default=datetime.datetime(2022, 10, 9, 2, 30, 20, 625685, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_createdate',
            field=models.DateField(default=datetime.datetime(2022, 10, 9, 2, 30, 20, 625685, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_locked',
            field=models.CharField(default=0, max_length=1, verbose_name='Locked'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_superuser',
            field=models.CharField(default=0, max_length=1, verbose_name='Superuser'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_updatedate',
            field=models.DateField(default=datetime.datetime(2022, 10, 9, 2, 30, 20, 625685, tzinfo=utc), null=True),
        ),
    ]
