# Generated by Django 4.0.7 on 2022-10-09 07:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('OUSR', '0012_alter_modules_user_createdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_email',
            field=models.CharField(default='test', max_length=100, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='user_username',
            field=models.CharField(default='test@gmail.com', max_length=100, verbose_name='Username'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='modules',
            name='user_createdate',
            field=models.DateField(default=datetime.datetime(2022, 10, 9, 7, 13, 57, 772872, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='modules',
            name='user_updatedate',
            field=models.DateField(default=datetime.datetime(2022, 10, 9, 7, 13, 57, 772872, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_createdate',
            field=models.DateField(default=datetime.datetime(2022, 10, 9, 7, 13, 57, 772872, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_updatedate',
            field=models.DateField(default=datetime.datetime(2022, 10, 9, 7, 13, 57, 772872, tzinfo=utc), null=True),
        ),
    ]
