# Generated by Django 4.0.7 on 2022-10-09 10:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('OUSR', '0013_profile_user_email_profile_user_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modules',
            name='user_createdate',
            field=models.DateField(default=datetime.datetime(2022, 10, 9, 10, 23, 11, 718904, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='modules',
            name='user_updatedate',
            field=models.DateField(default=datetime.datetime(2022, 10, 9, 10, 23, 11, 718904, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_createdate',
            field=models.DateField(default=datetime.datetime(2022, 10, 9, 10, 23, 11, 718904, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_updatedate',
            field=models.DateField(default=datetime.datetime(2022, 10, 9, 10, 23, 11, 718904, tzinfo=utc), null=True),
        ),
    ]
