# Generated by Django 4.0.7 on 2022-10-09 13:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('OUSR', '0014_alter_modules_user_createdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_modules',
            field=models.TextField(default='ousr,ocon,olic,oapp,oqut,odln,oinv,opor,opdn,ocrd,oitm,oige,owtq', verbose_name='Modules'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='modules',
            name='user_createdate',
            field=models.DateField(default=datetime.datetime(2022, 10, 9, 13, 44, 38, 566024, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='modules',
            name='user_updatedate',
            field=models.DateField(default=datetime.datetime(2022, 10, 9, 13, 44, 38, 566024, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_createdate',
            field=models.DateField(default=datetime.datetime(2022, 10, 9, 13, 44, 38, 566024, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_updatedate',
            field=models.DateField(default=datetime.datetime(2022, 10, 9, 13, 44, 38, 566024, tzinfo=utc), null=True),
        ),
    ]
