# Generated by Django 4.0.7 on 2022-10-09 15:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('OUSR', '0015_profile_user_modules_alter_modules_user_createdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_createdate',
            field=models.DateField(default=datetime.datetime(2022, 10, 9, 15, 5, 22, 141521, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_updatedate',
            field=models.DateField(default=datetime.datetime(2022, 10, 9, 15, 5, 22, 141521, tzinfo=utc), null=True),
        ),
        migrations.DeleteModel(
            name='Modules',
        ),
    ]
