# Generated by Django 4.0.7 on 2022-10-11 08:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('OUSR', '0016_alter_profile_user_createdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sapb1_employee_id',
            field=models.PositiveIntegerField(verbose_name='SAP B1 Employee ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_createdate',
            field=models.DateField(default=datetime.datetime(2022, 10, 11, 8, 47, 9, 927611, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_updatedate',
            field=models.DateField(default=datetime.datetime(2022, 10, 11, 8, 47, 9, 927611, tzinfo=utc), null=True),
        ),
    ]
