# Generated by Django 4.0.7 on 2022-10-13 16:30

import OUSR.models
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('OUSR', '0018_alter_profile_user_createdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_createdate',
            field=models.DateField(default=datetime.datetime(2022, 10, 13, 16, 30, 43, 530624, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_profilepic',
            field=models.ImageField(default='user-profile-pic/default.jpg', null=True, upload_to=OUSR.models.image_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_updatedate',
            field=models.DateField(default=datetime.datetime(2022, 10, 13, 16, 30, 43, 530624, tzinfo=utc), null=True),
        ),
    ]
