# Generated by Django 4.0.7 on 2022-10-13 16:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('OUSR', '0021_alter_profile_user_createdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rdr1',
            field=models.TextField(default='No Module', verbose_name='Modules'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_createdate',
            field=models.DateField(default=datetime.datetime(2022, 10, 13, 16, 45, 7, 988436, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_updatedate',
            field=models.DateField(default=datetime.datetime(2022, 10, 13, 16, 45, 7, 988436, tzinfo=utc), null=True),
        ),
    ]
