# Generated by Django 4.0.7 on 2022-10-13 16:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('OUSR', '0022_profile_rdr1_alter_profile_user_createdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rdr2',
            field=models.TextField(default='No Fields', verbose_name='Modules'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_createdate',
            field=models.DateField(default=datetime.datetime(2022, 10, 13, 16, 48, 7, 274920, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_updatedate',
            field=models.DateField(default=datetime.datetime(2022, 10, 13, 16, 48, 7, 274920, tzinfo=utc), null=True),
        ),
    ]
