# Generated by Django 4.0.7 on 2022-10-14 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OUSR', '0024_alter_profile_user_createdate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='rdr1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='rdr2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='sapb1_employee_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_createdate',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_database',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_locked',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_modules',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_profilepic',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_superuser',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_updatedate',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_username',
        ),
        migrations.AddField(
            model_name='profile',
            name='connectedNameOfField',
            field=models.CharField(max_length=100, null=True, verbose_name='connectedNameOfField'),
        ),
        migrations.AddField(
            model_name='profile',
            name='dataListFieldToSearch',
            field=models.CharField(max_length=100, null=True, verbose_name='dataListFieldToSearch'),
        ),
        migrations.AddField(
            model_name='profile',
            name='dataListID',
            field=models.CharField(max_length=100, null=True, verbose_name='dataListID'),
        ),
        migrations.AddField(
            model_name='profile',
            name='dataListTable',
            field=models.CharField(max_length=100, null=True, verbose_name='dataListTable'),
        ),
        migrations.AddField(
            model_name='profile',
            name='diapi',
            field=models.CharField(max_length=100, null=True, verbose_name='diapi'),
        ),
        migrations.AddField(
            model_name='profile',
            name='dnone',
            field=models.BooleanField(null=True, verbose_name='dnone'),
        ),
        migrations.AddField(
            model_name='profile',
            name='fieldId',
            field=models.CharField(max_length=100, null=True, verbose_name='fieldId'),
        ),
        migrations.AddField(
            model_name='profile',
            name='format',
            field=models.CharField(max_length=100, null=True, verbose_name='format'),
        ),
        migrations.AddField(
            model_name='profile',
            name='masterdata',
            field=models.CharField(max_length=100, null=True, verbose_name='masterdata'),
        ),
        migrations.AddField(
            model_name='profile',
            name='modal',
            field=models.CharField(max_length=100, null=True, verbose_name='modal'),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='profile',
            name='position',
            field=models.CharField(max_length=100, null=True, verbose_name='position'),
        ),
        migrations.AddField(
            model_name='profile',
            name='postable',
            field=models.BooleanField(null=True, verbose_name='postable'),
        ),
        migrations.AddField(
            model_name='profile',
            name='selectoptions',
            field=models.BooleanField(null=True, verbose_name='selectoptions'),
        ),
        migrations.AddField(
            model_name='profile',
            name='type',
            field=models.CharField(max_length=100, null=True, verbose_name='type'),
        ),
        migrations.AddField(
            model_name='profile',
            name='visible',
            field=models.BooleanField(null=True, verbose_name='visible'),
        ),
        migrations.AddField(
            model_name='profile',
            name='width',
            field=models.CharField(max_length=100, null=True, verbose_name='width'),
        ),
    ]
