# Generated by Django 4.0.7 on 2023-06-20 22:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OUSR', '0046_alter_profile_user_createdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_createdate',
            field=models.DateField(default=datetime.datetime(2023, 6, 20, 22, 41, 14, 172229), null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_updatedate',
            field=models.DateField(default=datetime.datetime(2023, 6, 20, 22, 41, 14, 172229), null=True),
        ),
    ]
