# Generated by Django 4.0.7 on 2023-03-30 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pctppod',
            options={'managed': False},
        ),
    ]
