# Generated by Django 4.0.7 on 2023-03-30 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_alter_pctppod_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pctppod',
            table='[@PCTP_POD]',
        ),
    ]
