# Generated by Django 4.0.7 on 2023-03-30 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_alter_pctppod_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pctppod',
            table='@PCTP_POD',
        ),
    ]
