# Generated by Django 4.1.9 on 2023-05-04 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_pctppricing_pctptp_alter_pctpbilling_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pctppricing',
            table='@PCTP_Pricing',
        ),
    ]
