# Generated by Django 4.0.7 on 2023-05-23 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_vehicletypeandcap'),
    ]

    operations = [
        migrations.CreateModel(
            name='PctpPodWindowRowModel',
            fields=[
                ('DisableTableRow', models.CharField(max_length=100)),
                ('Code', models.AutoField(primary_key=True, serialize=False)),
                ('U_BookingDate', models.DateField(blank=True)),
                ('U_BookingNumber', models.CharField(blank=True, max_length=100, unique=True)),
            ],
        ),
    ]
