# Generated by Django 4.0.7 on 2023-05-23 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_pctppodwindowrowmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pctppodwindowrowmodel',
            name='U_BookingNumber',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
