# Generated by Django 4.0.7 on 2023-05-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_alter_pctppodwindowrowmodel_u_bookingnumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pctppodwindowrowmodel',
            old_name='DisableTableRow',
            new_name='DisabledTableRow',
        ),
        migrations.AddField(
            model_name='pctppodwindowrowmodel',
            name='U_ActualDateRec_Intitial',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pctppodwindowrowmodel',
            name='U_ActualHCRecDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pctppodwindowrowmodel',
            name='U_ApprovalStatus',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pctppodwindowrowmodel',
            name='U_Approvedby',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pctppodwindowrowmodel',
            name='U_Attachment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pctppodwindowrowmodel',
            name='U_BTRemarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pctppodwindowrowmodel',
            name='U_BackLoad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pctppodwindowrowmodel',
            name='U_BillingDeadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pctppodwindowrowmodel',
            name='U_BillingNum',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='pctppodwindowrowmodel',
            name='U_BillingStatus',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pctppodwindowrowmodel',
            name='U_BillingTeam',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pctppodwindowrowmodel',
            name='U_CBM',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pctppodwindowrowmodel',
            name='U_CDC',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='pctppodwindowrowmodel',
            name='U_CategoryDR',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pctppodwindowrowmodel',
            name='U_ClientName',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='pctppodwindowrowmodel',
            name='U_ClientPenaltyCalc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pctppodwindowrowmodel',
            name='U_ClientReceivedDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pctppodwindowrowmodel',
            name='U_ClientSubOverdue',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pctppodwindowrowmodel',
            name='U_ClientSubStatus',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pctppodwindowrowmodel',
            name='U_DCD',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='pctppodwindowrowmodel',
            name='U_DateForwardedBT',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pctppodwindowrowmodel',
            name='U_DateReturned',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pctppodwindowrowmodel',
            name='U_DayOfTheWeek',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pctppodwindowrowmodel',
            name='U_DeliveryDateDTR',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pctppodwindowrowmodel',
            name='U_DeliveryDatePOD',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pctppodwindowrowmodel',
            name='U_DeliveryMode',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pctppodwindowrowmodel',
            name='U_DeliveryOrigin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pctppodwindowrowmodel',
            name='U_DeliveryReceiptNo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pctppodwindowrowmodel',
            name='U_DeliveryStatus',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pctppodwindowrowmodel',
            name='U_Destination',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pctppodwindowrowmodel',
            name='U_DestinationClient',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pctppodwindowrowmodel',
            name='U_DocNum',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pctppodwindowrowmodel',
            name='U_ForwardLoad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pctppodwindowrowmodel',
            name='U_GrossTruckerRates',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='pctppodwindowrowmodel',
            name='U_GroupProject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pctppodwindowrowmodel',
            name='U_HolidayOrWeekend',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pctppodwindowrowmodel',
            name='U_IDNumber',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pctppodwindowrowmodel',
            name='U_IFINTERISLAND',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='pctppodwindowrowmodel',
            name='U_InitialHCRecDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pctppodwindowrowmodel',
            name='U_InteluckPenaltyCalc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pctppodwindowrowmodel',
            name='U_Island',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pctppodwindowrowmodel',
            name='U_Island_D',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pctppodwindowrowmodel',
            name='U_LostPenaltyCalc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pctppodwindowrowmodel',
            name='U_NameCustomer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pctppodwindowrowmodel',
            name='U_NoOfDrops',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='pctppodwindowrowmodel',
            name='U_ODOIn',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pctppodwindowrowmodel',
            name='U_ODOOut',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pctppodwindowrowmodel',
            name='U_OtherPODDoc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pctppodwindowrowmodel',
            name='U_OutletNo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pctppodwindowrowmodel',
            name='U_OverdueDays',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='pctppodwindowrowmodel',
            name='U_PODSNum',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='pctppodwindowrowmodel',
            name='U_PODStatusDetail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pctppodwindowrowmodel',
            name='U_POD_TAT',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pctppodwindowrowmodel',
            name='U_PODinCharge',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pctppodwindowrowmodel',
            name='U_PTFNo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pctppodwindowrowmodel',
            name='U_PenaltiesManual',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='pctppodwindowrowmodel',
            name='U_PercPenaltyCharge',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pctppodwindowrowmodel',
            name='U_PlateNumber',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pctppodwindowrowmodel',
            name='U_PodStatusPayment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pctppodwindowrowmodel',
            name='U_PodSubmitDeadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pctppodwindowrowmodel',
            name='U_PricingNum',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='pctppodwindowrowmodel',
            name='U_Receiveby',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pctppodwindowrowmodel',
            name='U_Remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pctppodwindowrowmodel',
            name='U_Remarks2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pctppodwindowrowmodel',
            name='U_RemarksPOD',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pctppodwindowrowmodel',
            name='U_SAPClient',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='pctppodwindowrowmodel',
            name='U_SAPTrucker',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pctppodwindowrowmodel',
            name='U_SINo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pctppodwindowrowmodel',
            name='U_SI_DRNo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pctppodwindowrowmodel',
            name='U_SOBNumber',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pctppodwindowrowmodel',
            name='U_SONo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pctppodwindowrowmodel',
            name='U_SeriesNo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pctppodwindowrowmodel',
            name='U_ServiceType',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pctppodwindowrowmodel',
            name='U_ShipmentNo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pctppodwindowrowmodel',
            name='U_SourceWhse',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pctppodwindowrowmodel',
            name='U_TPNum',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='pctppodwindowrowmodel',
            name='U_TimeIn',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pctppodwindowrowmodel',
            name='U_TimeInAdvLoading',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pctppodwindowrowmodel',
            name='U_TimeInEmptyDem',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pctppodwindowrowmodel',
            name='U_TimeInLoadedDem',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pctppodwindowrowmodel',
            name='U_TimeOut',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pctppodwindowrowmodel',
            name='U_TimeOutEmptyDem',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pctppodwindowrowmodel',
            name='U_TimeOutLoadedDem',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pctppodwindowrowmodel',
            name='U_TotalInvAmount',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pctppodwindowrowmodel',
            name='U_TotalNoExceed',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='pctppodwindowrowmodel',
            name='U_TotalPenaltyWaived',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pctppodwindowrowmodel',
            name='U_TotalSubPenalties',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pctppodwindowrowmodel',
            name='U_TotalUsage',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='pctppodwindowrowmodel',
            name='U_TripTicketNo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pctppodwindowrowmodel',
            name='U_TripType',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pctppodwindowrowmodel',
            name='U_TruckerName',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='pctppodwindowrowmodel',
            name='U_TypeOfAccessorial',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pctppodwindowrowmodel',
            name='U_VERIFICATION_TAT',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pctppodwindowrowmodel',
            name='U_VehicleTypeCap',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pctppodwindowrowmodel',
            name='U_VerifiedDateHC',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pctppodwindowrowmodel',
            name='U_VerifiedEmptyDem',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pctppodwindowrowmodel',
            name='U_VerifiedLoadedDem',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pctppodwindowrowmodel',
            name='U_Waived',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pctppodwindowrowmodel',
            name='U_WaivedDays',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pctppodwindowrowmodel',
            name='U_WaybillNo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pctppodwindowrowmodel',
            name='U_BookingNumber',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
