# Generated by Django 4.0.7 on 2023-05-24 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0012_rename_u_podsnum_pctppodwindowrowmodel_u_podsonum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pctppodwindowrowmodel',
            old_name='DisabledTableRow',
            new_name='DisableTableRow',
        ),
    ]
