# Generated by Django 4.0.7 on 2023-05-24 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0013_rename_disabledtablerow_pctppodwindowrowmodel_disabletablerow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pctppodwindowrowmodel',
            name='U_ActualDateRec_Intitial',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pctppodwindowrowmodel',
            name='U_ActualHCRecDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pctppodwindowrowmodel',
            name='U_BillingDeadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pctppodwindowrowmodel',
            name='U_BookingDate',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='pctppodwindowrowmodel',
            name='U_ClientReceivedDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pctppodwindowrowmodel',
            name='U_DateForwardedBT',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pctppodwindowrowmodel',
            name='U_DateReturned',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pctppodwindowrowmodel',
            name='U_DeliveryDateDTR',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pctppodwindowrowmodel',
            name='U_DeliveryDatePOD',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pctppodwindowrowmodel',
            name='U_InitialHCRecDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pctppodwindowrowmodel',
            name='U_PodSubmitDeadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pctppodwindowrowmodel',
            name='U_VerifiedDateHC',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
