"""
Django settings for JCBAPortal project.

Generated by 'django-admin startproject' using Django 4.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-#4=h+586vs0)gkx8l@1%_ya=@#@1i-o-*-j5%+*_@f9-%hsam@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


############## SERVER CONFIG ################################
# SAP B1
server_name = 'JUSWA'
db_server_type = 10
sap_user_name = "manager"
sap_user_password = "sapb1"
user_trusted = "False"
# MS SQL
engine = 'mssql'
mssql_user_name = 'SA'
mssql_user_password = 'SAPB1Admin'
mssql_host = 'JUSWA' # This is the server name
mssql_port = '1443'
mssql_options = {
    'driver': 'ODBC Driver 17 for SQL Server'
}

print(engine)
print(mssql_user_name)
print(mssql_user_password)
############## SERVER CONFIG ################################


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'rest_framework',
    'debug_toolbar',
    # APIs
    'API.apps.ApiConfig',
    # SYSTEM MODULES
    'LOGIN.apps.LoginConfig',
    'DASHBOARD.apps.DashboardConfig',
    'OUSR.apps.OUSRConfig',
    'OADM.apps.OADMConfig',
    'ORDR.apps.ORDRConfig',
    # ADDON MODULES
    'ADDON_PCTP_UPLOADER_1.apps.AddonPctpUploader1Config',
    'ADDON_PCTP_WINDOW.apps.AddonPctpWindowConfig',
    
]

MIDDLEWARE = [
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django_session_timeout.middleware.SessionTimeoutMiddleware',
    'corsheaders.middleware.CorsMiddleware'
]

ROOT_URLCONF = 'JCBAPortal.urls'
JWT_AUTH = {
    # Authorization:Token xxx
    'JWT_AUTH_HEADER_PREFIX': 'Token',
}
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
            ],

          
        },
    },
]


WSGI_APPLICATION = 'JCBAPortal.wsgi.application'
REST_FRAMEWORK = {
    # other settings...

    'DEFAULT_AUTHENTICATION_CLASSES': [],
    'DEFAULT_PERMISSION_CLASSES': [],
}

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases
DATABASE_ROUTERS = ('API.dbrouters.MyDBRouter',)
DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': BASE_DIR / 'db.sqlite3',
    # }
    
    # engine = 'mssql'
    # mssql_user_name = 'SA'
    # mssql_user_password = 'SAPB1Admin'
    # mssql_host = 'JUSWA' # This is the server name
    # mssql_port = '1443'
    # mssql_options = {
    #     'driver': 'ODBC Driver 17 for SQL Server'
    # }

    'default': {
        'ENGINE': 'mssql',
        'NAME': 'PORTAL-USERS-COMMON',
        'USER': 'SA',
        'PASSWORD': 'SAPB1Admin',
        'HOST': 'JUSWA',
        'PORT': '1433',

        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
        },
    },
    'SBO-COMMON': {
        'ENGINE': 'mssql',
        'NAME': 'SBO-COMMON',
        'USER': 'SA',
        'PASSWORD': 'SAPB1Admin',
        'HOST': 'JUSWA',
        'PORT': '1433',

        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
        },
    },
    'SBODemoAU': {
        'ENGINE': 'mssql',
        'NAME': 'SBODemoAU',
        'USER': 'SA',
        'PASSWORD': 'SAPB1Admin',
        'HOST': 'JUSWA',
        'PORT': '1433',

        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
        },
    },
    'MPC_TEST_3': {
        'ENGINE': 'mssql',
        'NAME': 'MPC_TEST_3',
        'USER': 'SA',
        'PASSWORD': 'SAPB1Admin',
        'HOST': 'JUSWA',
        'PORT': '1433',

        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
        },
    },
    
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators
SESSION_EXPIRE_SECONDS = 11800  # Expire after 30 minutes
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Manila'

USE_I18N = True

# USE_TZ = True

# EMAIL


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
  # "../../SAPB1DjangoTest" + STATIC_URL
]

MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')
MEDIA_URL = '/media/'


# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

INTERNAL_IPS = [
    '127.0.0.1',
]
