from django.db import models

# Create your models here.


#####################################################################################################################################################################
################# PCTP MODELS ###############################
#####################################################################################################################################################################
################# PCTP POD WINDOW ROW VIEW
class PctpPodWindowRowModel (models.Model):
    DisableTableRow = models.CharField(max_length=2)  # Customized field
    Code = models.AutoField(primary_key=True)  
    U_BookingDate = models.DateTimeField(blank=True)  
    U_BookingNumber = models.CharField(max_length=100, blank=True,unique=True)  
    U_PODSONum = models.CharField(max_length=25, blank=True, null=True)  
    U_ClientName = models.CharField(max_length=254, blank=True, null=True)  
    U_SAPClient = models.CharField(max_length=254, blank=True, null=True)  
    U_TruckerName = models.CharField(max_length=254, blank=True, null=True)  
    U_Island = models.CharField( max_length=50, blank=True, null=True)  
    U_Island_D = models.CharField(max_length=50, blank=True, null=True)  
    U_IFINTERISLAND = models.CharField(max_length=10, blank=True, null=True)  
    U_VERIFICATION_TAT = models.IntegerField( blank=True, null=True)  
    U_POD_TAT = models.IntegerField(blank=True, null=True)  
    U_ActualDateRec_Intitial = models.DateTimeField( blank=True, null=True)  
    U_SAPTrucker = models.CharField(max_length=100, blank=True, null=True)  
    U_PlateNumber = models.CharField(max_length=50, blank=True, null=True)  
    U_VehicleTypeCap = models.CharField(max_length=50, blank=True, null=True)  
    U_DeliveryStatus = models.CharField(max_length=50, blank=True, null=True)  # Field name made lower
    U_DeliveryDateDTR = models.DateTimeField( blank=True, null=True)  
    U_DeliveryDatePOD = models.DateTimeField( blank=True, null=True)  
    U_NoOfDrops = models.DecimalField(max_digits=19, decimal_places=6, blank=True, null=True)  
    U_TripType = models.CharField(max_length=100, blank=True, null=True)  
    U_Receiveby = models.CharField(max_length=100, blank=True, null=True)  
    U_ClientReceivedDate = models.DateTimeField( blank=True, null=True)  
    U_InitialHCRecDate = models.DateTimeField(blank=True, null=True)  
    U_ActualHCRecDate = models.DateTimeField(blank=True, null=True)  
    U_DateReturned = models.DateTimeField(blank=True, null=True)  
    U_PODinCharge = models.CharField(max_length=100, blank=True, null=True)  
    U_VerifiedDateHC = models.DateTimeField(blank=True, null=True)  
    U_PTFNo = models.CharField( max_length=100, blank=True, null=True)  
    U_DateForwardedBT = models.DateTimeField( blank=True, null=True)  
    U_BillingDeadline = models.DateTimeField(blank=True, null=True)  
    U_BillingStatus = models.CharField(max_length=100, blank=True, null=True)  
    U_ServiceType = models.CharField( max_length=50, blank=True, null=True)  
    U_SINo = models.CharField( max_length=100, blank=True, null=True)  
    U_BillingTeam = models.CharField(max_length=100, blank=True, null=True)  
    U_SOBNumber = models.CharField( max_length=100, blank=True, null=True)  
    U_ForwardLoad = models.CharField( max_length=100, blank=True, null=True)  
    U_BackLoad = models.CharField( max_length=100, blank=True, null=True)  
    U_TypeOfAccessorial = models.CharField(max_length=50, blank=True, null=True)  
    U_TimeInEmptyDem = models.CharField( max_length=50, blank=True, null=True)  
    U_TimeOutEmptyDem = models.CharField(max_length=50, blank=True, null=True)  
    U_VerifiedEmptyDem = models.CharField(max_length=50, blank=True, null=True)  
    U_TimeInLoadedDem = models.CharField(max_length=50, blank=True, null=True)  
    U_TimeOutLoadedDem = models.CharField(max_length=50, blank=True, null=True)  
    U_VerifiedLoadedDem = models.CharField( max_length=50, blank=True, null=True)  
    U_TimeInAdvLoading = models.CharField(max_length=50, blank=True, null=True)  
    U_PenaltiesManual = models.DecimalField(max_digits=19, decimal_places=6, blank=True, null=True)  
    U_DayOfTheWeek = models.CharField( max_length=50, blank=True, null=True)  
    U_TimeIn = models.CharField( max_length=50, blank=True, null=True)  
    U_TimeOut = models.CharField( max_length=50, blank=True, null=True)  
    U_TotalNoExceed = models.DecimalField(max_digits=19, decimal_places=6, blank=True, null=True)  
    U_ODOIn = models.CharField( max_length=50, blank=True, null=True)  
    U_ODOOut = models.CharField(max_length=50, blank=True, null=True)  
    U_TotalUsage = models.DecimalField(max_digits=19, decimal_places=6, blank=True, null=True)  
    U_ClientSubStatus = models.CharField( max_length=100, blank=True, null=True)  
    U_ClientSubOverdue = models.CharField(max_length=50, blank=True, null=True)  
    U_ClientPenaltyCalc = models.CharField( max_length=50, blank=True, null=True)  
    U_PodStatusPayment = models.CharField( max_length=50, blank=True, null=True)  
    U_PodSubmitDeadline = models.DateTimeField( blank=True, null=True)  
    U_OverdueDays = models.CharField( max_length=25, blank=True, null=True)  
    U_InteluckPenaltyCalc = models.CharField( max_length=50, blank=True, null=True)  
    U_WaivedDays = models.CharField(max_length=20, blank=True, null=True)  
    U_HolidayOrWeekend = models.CharField( max_length=50, blank=True, null=True)  
    U_LostPenaltyCalc = models.CharField(max_length=50, blank=True, null=True)  
    U_TotalSubPenalties = models.CharField( max_length=50, blank=True, null=True)  
    U_Waived = models.CharField( max_length=50, blank=True, null=True)  
    U_PercPenaltyCharge = models.CharField( max_length=50, blank=True, null=True)  
    U_Approvedby = models.CharField( max_length=100, blank=True, null=True)  
    U_TotalPenaltyWaived = models.CharField( max_length=50, blank=True, null=True)  
    U_BillingNum = models.DecimalField(max_digits=19, decimal_places=6, blank=True, null=True)  
    U_TPNum = models.DecimalField(max_digits=19, decimal_places=6, blank=True, null=True)  
    U_PricingNum = models.DecimalField(max_digits=19, decimal_places=6, blank=True, null=True)  
    U_CDC = models.DecimalField(max_digits=19, decimal_places=6, blank=True, null=True)  
    U_DCD = models.DecimalField(max_digits=19, decimal_places=6, blank=True, null=True)  
    U_GrossTruckerRates = models.DecimalField(max_digits=19, decimal_places=6, blank=True, null=True)  
    U_GroupProject = models.CharField(max_length=100, blank=True, null=True)  
    U_Attachment = models.TextField(blank=True, null=True)  
    U_DeliveryOrigin = models.TextField(blank=True, null=True)  
    U_Destination = models.TextField(blank=True, null=True)  
    U_Remarks = models.TextField( blank=True, null=True)  
    U_OtherPODDoc = models.TextField( blank=True, null=True)  
    U_RemarksPOD = models.TextField( blank=True, null=True)  
    U_PODStatusDetail = models.TextField( blank=True, null=True)  
    U_BTRemarks = models.TextField(blank=True, null=True)  
    U_DestinationClient = models.TextField(blank=True, null=True)  
    U_Remarks2 = models.TextField( blank=True, null=True)  
    U_DocNum = models.TextField( blank=True, null=True)  
    U_TripTicketNo = models.TextField( blank=True, null=True)  
    U_WaybillNo = models.TextField(blank=True, null=True)  
    U_ShipmentNo = models.TextField(blank=True, null=True)  
    U_DeliveryReceiptNo = models.TextField( blank=True, null=True)  
    U_SeriesNo = models.TextField(blank=True, null=True)  
    U_OutletNo = models.TextField(blank=True, null=True)  
    U_CBM = models.TextField(blank=True, null=True)  
    U_SI_DRNo = models.TextField( blank=True, null=True)  
    U_DeliveryMode = models.TextField(blank=True, null=True)  
    U_SourceWhse = models.TextField( blank=True, null=True)  
    U_SONo = models.TextField( blank=True, null=True)  
    U_NameCustomer = models.TextField( blank=True, null=True)  
    U_CategoryDR = models.TextField(blank=True, null=True)  
    U_IDNumber = models.TextField(blank=True, null=True)  
    U_ApprovalStatus = models.TextField( blank=True, null=True)  
    U_TotalInvAmount = models.TextField(blank=True, null=True)  

################# PCTP VEHICLE TYPE AND CAPACITY
class Vehicletypeandcap(models.Model):
    Code = models.CharField(db_column='Code', unique=True, primary_key=True, max_length=100)  
    Name = models.CharField(db_column='Name', unique=True, max_length=100)  

    class Meta:
        managed = False
        db_table = '@VEHICLETYPEANDCAP'

################# PCTP DELIVERY STATUS
class DeliveryStatus(models.Model):
    Code = models.CharField(db_column='Code', primary_key=True, max_length=50)  # Field name made lowercase.
    Name = models.CharField(db_column='Name', unique=True, max_length=100)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = '@DELIVERYSTATUS'

################# PCTP POD
class PctpPod(models.Model):
    code = models.AutoField(db_column='Code', primary_key=True)  
    name = models.CharField(db_column='Name', max_length=100, blank=True)  
    u_bookingdate = models.DateTimeField(db_column='U_BookingDate', blank=True)  
    u_bookingnumber = models.CharField(db_column='U_BookingNumber', max_length=100, blank=True,unique=True)  
    u_clientname = models.CharField(db_column='U_ClientName', max_length=254, blank=True, null=True)  
    u_sapclient = models.CharField(db_column='U_SAPClient', max_length=254, blank=True, null=True)  
    u_truckername = models.CharField(db_column='U_TruckerName', max_length=100, blank=True, null=True)  
    u_saptrucker = models.CharField(db_column='U_SAPTrucker', max_length=100, blank=True, null=True)  
    u_platenumber = models.CharField(db_column='U_PlateNumber', max_length=50, blank=True, null=True)  
    u_vehicletypecap = models.CharField(db_column='U_VehicleTypeCap', max_length=50, blank=True, null=True)  
    u_deliverystatus = models.CharField(db_column='U_DeliveryStatus', max_length=50, blank=True, null=True)  
    u_deliverydatedtr = models.DateTimeField(db_column='U_DeliveryDateDTR', blank=True, null=True)  
    u_deliverydatepod = models.DateTimeField(db_column='U_DeliveryDatePOD', blank=True, null=True)  
    u_noofdrops = models.DecimalField(db_column='U_NoOfDrops', max_digits=19, decimal_places=6, blank=True, null=True)  
    u_triptype = models.CharField(db_column='U_TripType', max_length=100, blank=True, null=True)  
    u_remarks = models.TextField(db_column='U_Remarks', blank=True, null=True)  
    u_otherpoddoc = models.TextField(db_column='U_OtherPODDoc', blank=True, null=True)  
    u_remarkspod = models.TextField(db_column='U_RemarksPOD', blank=True, null=True)  
    u_receivedby = models.CharField(db_column='U_Receivedby', max_length=100, blank=True, null=True)  
    u_clientreceiveddate = models.DateTimeField(db_column='U_ClientReceivedDate', blank=True, null=True)  
    u_initialhcrecdate = models.DateTimeField(db_column='U_InitialHCRecDate', blank=True, null=True)  
    u_actualhcrecdate = models.DateTimeField(db_column='U_ActualHCRecDate', blank=True, null=True)  
    u_datereturned = models.DateTimeField(db_column='U_DateReturned', blank=True, null=True)  
    u_podincharge = models.CharField(db_column='U_PODinCharge', max_length=100, blank=True, null=True)  
    u_verifieddatehc = models.DateTimeField(db_column='U_VerifiedDateHC', blank=True, null=True)  
    u_podstatusdetail = models.TextField(db_column='U_PODStatusDetail', blank=True, null=True)  
    u_ptfno = models.CharField(db_column='U_PTFNo', max_length=100, blank=True, null=True)  
    u_dateforwardedbt = models.DateTimeField(db_column='U_DateForwardedBT', blank=True, null=True)  
    u_billingdeadline = models.DateTimeField(db_column='U_BillingDeadline', blank=True, null=True)  
    u_billingstatus = models.CharField(db_column='U_BillingStatus', max_length=100, blank=True, null=True)  
    u_servicetype = models.CharField(db_column='U_ServiceType', max_length=50, blank=True, null=True)  
    u_sino = models.CharField(db_column='U_SINo', max_length=100, blank=True, null=True)  
    u_billingteam = models.CharField(db_column='U_BillingTeam', max_length=100, blank=True, null=True)  
    u_btremarks = models.TextField(db_column='U_BTRemarks', blank=True, null=True)  
    u_sobnumber = models.CharField(db_column='U_SOBNumber', max_length=100, blank=True, null=True)  
    u_forwardload = models.CharField(db_column='U_ForwardLoad', max_length=100, blank=True, null=True)  
    u_backload = models.CharField(db_column='U_BackLoad', max_length=100, blank=True, null=True)  
    u_typeofaccessorial = models.CharField(db_column='U_TypeOfAccessorial', max_length=50, blank=True, null=True)  
    u_timeinemptydem = models.CharField(db_column='U_TimeInEmptyDem', max_length=50, blank=True, null=True)  
    u_timeoutemptydem = models.CharField(db_column='U_TimeOutEmptyDem', max_length=50, blank=True, null=True)  
    u_verifiedemptydem = models.CharField(db_column='U_VerifiedEmptyDem', max_length=50, blank=True, null=True)  
    u_timeinloadeddem = models.CharField(db_column='U_TimeInLoadedDem', max_length=50, blank=True, null=True)  
    u_timeoutloadeddem = models.CharField(db_column='U_TimeOutLoadedDem', max_length=50, blank=True, null=True)  
    u_verifiedloadeddem = models.CharField(db_column='U_VerifiedLoadedDem', max_length=50, blank=True, null=True)  
    u_remarks2 = models.TextField(db_column='U_Remarks2', blank=True, null=True)  
    u_timeinadvloading = models.CharField(db_column='U_TimeInAdvLoading', max_length=50, blank=True, null=True)  
    u_dayoftheweek = models.CharField(db_column='U_DayOfTheWeek', max_length=50, blank=True, null=True)  
    u_timein = models.CharField(db_column='U_TimeIn', max_length=50, blank=True, null=True)  
    u_timeout = models.CharField(db_column='U_TimeOut', max_length=50, blank=True, null=True)  
    u_odoin = models.CharField(db_column='U_ODOIn', max_length=50, blank=True, null=True)  
    u_odoout = models.CharField(db_column='U_ODOOut', max_length=50, blank=True, null=True)  
    u_clientsubstatus = models.CharField(db_column='U_ClientSubStatus', max_length=100, blank=True, null=True)  
    u_clientsuboverdue = models.CharField(db_column='U_ClientSubOverdue', max_length=50, blank=True, null=True)  
    u_clientpenaltycalc = models.CharField(db_column='U_ClientPenaltyCalc', max_length=50, blank=True, null=True)  
    u_podstatuspayment = models.CharField(db_column='U_PODStatusPayment', max_length=50, blank=True, null=True)  
    u_podsubmitdeadline = models.DateTimeField(db_column='U_PODSubmitDeadline', blank=True, null=True)  
    u_overduedays = models.CharField(db_column='U_OverdueDays', max_length=25, blank=True, null=True)  
    u_inteluckpenaltycalc = models.CharField(db_column='U_InteluckPenaltyCalc', max_length=50, blank=True, null=True)  
    u_waiveddays = models.CharField(db_column='U_WaivedDays', max_length=50, blank=True, null=True)  
    u_holidayorweekend = models.CharField(db_column='U_HolidayOrWeekend', max_length=50, blank=True, null=True)  
    u_lostpenaltycalc = models.CharField(db_column='U_LostPenaltyCalc', max_length=50, blank=True, null=True)  
    u_totalsubpenalties = models.CharField(db_column='U_TotalSubPenalties', max_length=50, blank=True, null=True)  
    u_waived = models.CharField(db_column='U_Waived', max_length=50, blank=True, null=True)  
    u_percpenaltycharge = models.CharField(db_column='U_PercPenaltyCharge', max_length=50, blank=True, null=True)  
    u_approvedby = models.CharField(db_column='U_Approvedby', max_length=100, blank=True, null=True)  
    u_totalpenaltywaived = models.CharField(db_column='U_TotalPenaltyWaived', max_length=50, blank=True, null=True)  
    u_updatedate = models.DateTimeField(db_column='U_UpdateDate', blank=True, null=True)  
    u_createdate = models.DateTimeField(db_column='U_CreateDate', blank=True, null=True)  
    u_attachment = models.TextField(db_column='U_Attachment', blank=True, null=True)  
    u_creator = models.CharField(db_column='U_Creator', max_length=50, blank=True, null=True)  
    u_totalnoexceed = models.DecimalField(db_column='U_TotalNoExceed', max_digits=19, decimal_places=6, blank=True, null=True)  
    u_totalusage = models.DecimalField(db_column='U_TotalUsage', max_digits=19, decimal_places=6, blank=True, null=True)  
    u_penaltiesmanual = models.DecimalField(db_column='U_PenaltiesManual', max_digits=19, decimal_places=6, blank=True, null=True)  
    u_island = models.CharField(db_column='U_ISLAND', max_length=50, blank=True, null=True)  
    u_island_d = models.CharField(db_column='U_ISLAND_D', max_length=50, blank=True, null=True)  
    u_ifinterisland = models.CharField(db_column='U_IFINTERISLAND', max_length=10, blank=True, null=True)  
    u_verification_tat = models.IntegerField(db_column='U_VERIFICATION_TAT', blank=True, null=True)  
    u_pod_tat = models.IntegerField(db_column='U_POD_TAT', blank=True, null=True)  
    u_actualdaterec_intitial = models.DateTimeField(db_column='U_ActualDateRec_Intitial', blank=True, null=True)  
    u_deliveryorigin = models.TextField(db_column='U_DeliveryOrigin', blank=True, null=True)  
    u_destination = models.TextField(db_column='U_Destination', blank=True, null=True)  
    u_destinationclient = models.TextField(db_column='U_DestinationClient', blank=True, null=True)  
    u_tripticketno = models.TextField(db_column='U_TripTicketNo', blank=True, null=True)  
    u_waybillno = models.TextField(db_column='U_WaybillNo', blank=True, null=True)  
    u_shipmentno = models.TextField(db_column='U_ShipmentNo', blank=True, null=True)  
    u_deliveryreceiptno = models.TextField(db_column='U_DeliveryReceiptNo', blank=True, null=True)  
    u_seriesno = models.TextField(db_column='U_SeriesNo', blank=True, null=True)  
    u_outletno = models.TextField(db_column='U_OutletNo', blank=True, null=True)  
    u_cbm = models.TextField(db_column='U_CBM', blank=True, null=True)  
    u_si_drno = models.TextField(db_column='U_SI_DRNo', blank=True, null=True)  
    u_deliverymode = models.TextField(db_column='U_DeliveryMode', blank=True, null=True)  
    u_sourcewhse = models.TextField(db_column='U_SourceWhse', blank=True, null=True)  
    u_sono = models.TextField(db_column='U_SONo', blank=True, null=True)  
    u_namecustomer = models.TextField(db_column='U_NameCustomer', blank=True, null=True)  
    u_categorydr = models.TextField(db_column='U_CategoryDR', blank=True, null=True)  
    u_idnumber = models.TextField(db_column='U_IDNumber', blank=True, null=True)  
    u_approvalstatus = models.TextField(db_column='U_ApprovalStatus', blank=True, null=True)  
    u_docnum = models.TextField(db_column='U_DocNum', blank=True, null=True)  
    u_totalinvamount = models.TextField(db_column='U_TotalInvAmount', blank=True, null=True)  
    u_editing = models.CharField(db_column='U_Editing', max_length=10, blank=True, null=True)  

    class Meta:
        managed = False
        db_table = '@PCTP_POD'
    

################# PCTP BILLING
class PctpBilling(models.Model):
    code = models.AutoField(db_column='Code', primary_key=True)  
    name = models.CharField(db_column='Name', max_length=100, blank=True, null=True)  
    u_bookingid = models.CharField(db_column='U_BookingId', max_length=50, blank=True)  
    u_bookingdate = models.DateTimeField(db_column='U_BookingDate', blank=True, null=True)  
    u_customername = models.CharField(db_column='U_CustomerName', max_length=254, blank=True, null=True)  
    u_sapclient = models.CharField(db_column='U_SAPClient', max_length=100, blank=True, null=True)  
    u_groupproject = models.CharField(db_column='U_GroupProject', max_length=100, blank=True, null=True)  
    u_platenumber = models.CharField(db_column='U_PlateNumber', max_length=100, blank=True, null=True)  
    u_vehicletypecap = models.CharField(db_column='U_VehicleTypeCap', max_length=50, blank=True, null=True)  
    u_deliverystatus = models.CharField(db_column='U_DeliveryStatus', max_length=50, blank=True, null=True)  
    u_deliverydatepod = models.DateTimeField(db_column='U_DeliveryDatePOD', blank=True, null=True)  
    u_triptype = models.CharField(db_column='U_TripType', max_length=50, blank=True, null=True)  
    u_waybillno = models.CharField(db_column='U_WaybillNo', max_length=100, blank=True, null=True)  
    u_shipmentmanifestno = models.CharField(db_column='U_ShipmentManifestNo', max_length=100, blank=True, null=True)  
    u_deliveryreceiptno = models.CharField(db_column='U_DeliveryReceiptNo', max_length=100, blank=True, null=True)  
    u_seriesno = models.CharField(db_column='U_SeriesNo', max_length=100, blank=True, null=True)  
    u_otherpoddoc = models.TextField(db_column='U_OtherPODDoc', blank=True, null=True)  
    u_remarkspod = models.TextField(db_column='U_RemarksPOD', blank=True, null=True)  
    u_clientreceiveddate = models.DateTimeField(db_column='U_ClientReceivedDate', blank=True, null=True)  
    u_actualhcrecdate = models.DateTimeField(db_column='U_ActualHCRecDate', blank=True, null=True)  
    u_podincharge = models.CharField(db_column='U_PODinCharge', max_length=100, blank=True, null=True)  
    u_verifieddatehc = models.DateTimeField(db_column='U_VerifiedDateHC', blank=True, null=True)  
    u_podstatusdetail = models.TextField(db_column='U_PODStatusDetail', blank=True, null=True)  
    u_ptfno = models.CharField(db_column='U_PTFNo', max_length=100, blank=True, null=True)  
    u_dateforwardedbt = models.DateTimeField(db_column='U_DateForwardedBT', blank=True, null=True)  
    u_billingdeadline = models.DateTimeField(db_column='U_BillingDeadline', blank=True, null=True)  
    u_billingstatus = models.CharField(db_column='U_BillingStatus', max_length=50, blank=True, null=True)  
    u_servicetype = models.CharField(db_column='U_ServiceType', max_length=50, blank=True, null=True)  
    u_sino = models.CharField(db_column='U_SINo', max_length=100, blank=True, null=True)  
    u_billingteam = models.CharField(db_column='U_BillingTeam', max_length=100, blank=True, null=True)  
    u_btremarks = models.TextField(db_column='U_BTRemarks', blank=True, null=True)  
    u_grossinitialrate = models.DecimalField(db_column='U_GrossInitialRate', max_digits=19, decimal_places=6, blank=True, null=True)  
    u_actualbilledrate = models.DecimalField(db_column='U_ActualBilledRate', max_digits=19, decimal_places=6, blank=True, null=True)  
    u_rateadjustments = models.DecimalField(db_column='U_RateAdjustments', max_digits=19, decimal_places=6, blank=True, null=True)  
    u_actualdemurrage = models.DecimalField(db_column='U_ActualDemurrage', max_digits=19, decimal_places=6, blank=True, null=True)  
    u_actualaddcharges = models.DecimalField(db_column='U_ActualAddCharges', max_digits=19, decimal_places=6, blank=True, null=True)  
    u_totalrecclients = models.DecimalField(db_column='U_TotalRecClients', max_digits=19, decimal_places=6, blank=True, null=True)  
    u_checkingtotalbilled = models.DecimalField(db_column='U_CheckingTotalBilled', max_digits=19, decimal_places=6, blank=True, null=True)  
    u_checking = models.DecimalField(db_column='U_Checking', max_digits=19, decimal_places=6, blank=True, null=True)  
    u_sobnumber = models.CharField(db_column='U_SOBNumber', max_length=100, blank=True, null=True)  
    u_outletno = models.CharField(db_column='U_OutletNo', max_length=100, blank=True, null=True)  
    u_cbm = models.CharField(db_column='U_CBM', max_length=100, blank=True, null=True)  
    u_si_drno = models.CharField(db_column='U_SI_DRNo', max_length=100, blank=True, null=True)  
    u_deliverymode = models.CharField(db_column='U_DeliveryMode', max_length=100, blank=True, null=True)  
    u_sourcewhse = models.CharField(db_column='U_SourceWhse', max_length=100, blank=True, null=True)  
    u_totalinvamount = models.DecimalField(db_column='U_TotalInvAmount', max_digits=19, decimal_places=6, blank=True, null=True)  
    u_sono = models.CharField(db_column='U_SONo', max_length=100, blank=True, null=True)  
    u_namecustomer = models.CharField(db_column='U_NameCustomer', max_length=254, blank=True, null=True)  
    u_categorydr = models.CharField(db_column='U_CategoryDR', max_length=50, blank=True, null=True)  
    u_forwardload = models.CharField(db_column='U_ForwardLoad', max_length=100, blank=True, null=True)  
    u_backload = models.CharField(db_column='U_BackLoad', max_length=100, blank=True, null=True)  
    u_idnumber = models.CharField(db_column='U_IDNumber', max_length=100, blank=True, null=True)  
    u_typeofaccessorial = models.CharField(db_column='U_TypeOfAccessorial', max_length=50, blank=True, null=True)  
    u_status = models.CharField(db_column='U_Status', max_length=50, blank=True, null=True)  
    u_timeinemptydem = models.CharField(db_column='U_TimeInEmptyDem', max_length=50, blank=True, null=True)  
    u_timeoutemptydem = models.CharField(db_column='U_TimeOutEmptyDem', max_length=50, blank=True, null=True)  
    u_verifiedemptydem = models.CharField(db_column='U_VerifiedEmptyDem', max_length=50, blank=True, null=True)  
    u_timeinloadeddem = models.CharField(db_column='U_TimeInLoadedDem', max_length=50, blank=True, null=True)  
    u_timeoutloadeddem = models.CharField(db_column='U_TimeOutLoadedDem', max_length=50, blank=True, null=True)  
    u_verifiedloadeddem = models.CharField(db_column='U_VerifiedLoadedDem', max_length=50, blank=True, null=True)  
    u_remarks = models.TextField(db_column='U_Remarks', blank=True, null=True)  
    u_timeinadvloading = models.CharField(db_column='U_TimeInAdvLoading', max_length=50, blank=True, null=True)  
    u_dayoftheweek = models.CharField(db_column='U_DayOfTheWeek', max_length=50, blank=True, null=True)  
    u_timein = models.CharField(db_column='U_TimeIn', max_length=50, blank=True, null=True)  
    u_timeout = models.CharField(db_column='U_TimeOut', max_length=50, blank=True, null=True)  
    u_odoin = models.CharField(db_column='U_ODOIn', max_length=50, blank=True, null=True)  
    u_odoout = models.CharField(db_column='U_ODOOut', max_length=50, blank=True, null=True)  
    u_docnum = models.CharField(db_column='U_DocNum', max_length=254, blank=True, null=True)  
    u_podnum = models.CharField(db_column='U_PODNum', max_length=25, blank=True, null=True)  
    u_podsonum = models.CharField(db_column='U_PODSONum', max_length=25, blank=True, null=True)  
    u_updatedate = models.DateTimeField(db_column='U_UpdateDate', blank=True, null=True)  
    u_createdate = models.DateTimeField(db_column='U_CreateDate', blank=True, null=True)  
    u_updatetime = models.SmallIntegerField(db_column='U_UpdateTime', blank=True, null=True)  
    u_demurrage = models.DecimalField(db_column='U_Demurrage', max_digits=19, decimal_places=6, blank=True, null=True)  
    u_addcharges = models.DecimalField(db_column='U_AddCharges', max_digits=19, decimal_places=6, blank=True, null=True)  
    u_cwt2307 = models.DecimalField(db_column='U_CWT2307', max_digits=19, decimal_places=6, blank=True, null=True)  
    u_arinvlinenum = models.CharField(db_column='U_ARInvLineNum', max_length=10, blank=True, null=True)  
    u_noofdrops = models.DecimalField(db_column='U_NoOfDrops', max_digits=19, decimal_places=6, blank=True, null=True)  
    u_solinenum = models.CharField(db_column='U_SOLineNum', max_length=10, blank=True, null=True)  
    u_totalexceed = models.DecimalField(db_column='U_TotalExceed', max_digits=19, decimal_places=6, blank=True, null=True)  
    u_totalusage = models.DecimalField(db_column='U_TotalUsage', max_digits=19, decimal_places=6, blank=True, null=True)  
    u_deliveryorigin = models.TextField(db_column='U_DeliveryOrigin', blank=True, null=True)  
    u_destination = models.TextField(db_column='U_Destination', blank=True, null=True)  
    u_destinationclient = models.TextField(db_column='U_DestinationClient', blank=True, null=True)  
    u_totalar = models.DecimalField(db_column='U_TotalAR', max_digits=19, decimal_places=6, blank=True, null=True)  
    u_varar = models.DecimalField(db_column='U_VarAR', max_digits=19, decimal_places=6, blank=True, null=True)  

    class Meta:
        managed = False
        db_table = '@PCTP_Billing'

################# PCTP TP
class PctpTp(models.Model):
    code = models.AutoField(db_column='Code', primary_key=True)  
    name = models.CharField(db_column='Name', max_length=100, blank=True, null=True)  
    u_bookingid = models.CharField(db_column='U_BookingId', max_length=50, blank=True)  
    u_bookingdate = models.DateTimeField(db_column='U_BookingDate', blank=True, null=True)  
    u_clientname = models.CharField(db_column='U_ClientName', max_length=254, blank=True, null=True)  
    u_truckername = models.CharField(db_column='U_TruckerName', max_length=100, blank=True, null=True)  
    u_truckersap = models.CharField(db_column='U_TruckerSAP', max_length=100, blank=True, null=True)  
    u_deliverystatus = models.CharField(db_column='U_DeliveryStatus', max_length=50, blank=True, null=True)  
    u_deliverydatepod = models.DateTimeField(db_column='U_DeliveryDatePOD', blank=True, null=True)  
    u_tripticketno = models.CharField(db_column='U_TripTicketNo', max_length=100, blank=True, null=True)  
    u_waybillno = models.CharField(db_column='U_WaybillNo', max_length=100, blank=True, null=True)  
    u_shipmentmanifestno = models.CharField(db_column='U_ShipmentManifestNo', max_length=100, blank=True, null=True)  
    u_deliveryreceiptno = models.CharField(db_column='U_DeliveryReceiptNo', max_length=100, blank=True, null=True)  
    u_seriesno = models.CharField(db_column='U_SeriesNo', max_length=100, blank=True, null=True)  
    u_otherpoddoc = models.TextField(db_column='U_OtherPODDoc', blank=True, null=True)  
    u_tpstatus = models.CharField(db_column='U_TPStatus', max_length=100, blank=True, null=True)  
    u_grosstruckerrates = models.DecimalField(db_column='U_GrossTruckerRates', max_digits=19, decimal_places=6, blank=True, null=True)  
    u_grosstruckerratesn = models.DecimalField(db_column='U_GrossTruckerRatesN', max_digits=19, decimal_places=6, blank=True, null=True)  
    u_ratebasis = models.CharField(db_column='U_RateBasis', max_length=50, blank=True, null=True)  
    u_taxtype = models.CharField(db_column='U_TaxType', max_length=50, blank=True, null=True)  
    u_demurrage = models.CharField(db_column='U_Demurrage', max_length=50, blank=True, null=True)  
    u_addtldrop = models.CharField(db_column='U_AddtlDrop', max_length=50, blank=True, null=True)  
    u_boomtruck = models.CharField(db_column='U_BoomTruck', max_length=50, blank=True, null=True)  
    u_manpower = models.CharField(db_column='U_Manpower', max_length=50, blank=True, null=True)  
    u_backload = models.CharField(db_column='U_BackLoad', max_length=50, blank=True, null=True)  
    u_addtlcharges = models.DecimalField(db_column='U_Addtlcharges', max_digits=19, decimal_places=6, blank=True, null=True)  
    u_demurragen = models.CharField(db_column='U_DemurrageN', max_length=50, blank=True, null=True)  
    u_addtlchargesn = models.CharField(db_column='U_AddtlChargesN', max_length=50, blank=True, null=True)  
    u_actualrates = models.DecimalField(db_column='U_ActualRates', max_digits=19, decimal_places=6, blank=True, null=True)  
    u_rateadjustments = models.DecimalField(db_column='U_RateAdjustments', max_digits=19, decimal_places=6, blank=True, null=True)  
    u_actualdemurrage = models.CharField(db_column='U_ActualDemurrage', max_length=50, blank=True, null=True)  
    u_actualcharges = models.DecimalField(db_column='U_ActualCharges', max_digits=19, decimal_places=6, blank=True, null=True)  
    u_boomtruck2 = models.CharField(db_column='U_BoomTruck2', max_length=50, blank=True, null=True)  
    u_othercharges = models.DecimalField(db_column='U_OtherCharges', max_digits=19, decimal_places=6, blank=True, null=True)  
    u_totalsubpenalty = models.DecimalField(db_column='U_TotalSubPenalty', max_digits=19, decimal_places=6, blank=True, null=True)  
    u_totalpenaltywaived = models.DecimalField(db_column='U_TotalPenaltyWaived', max_digits=19, decimal_places=6, blank=True, null=True)  
    u_totalpenalty = models.DecimalField(db_column='U_TotalPenalty', max_digits=19, decimal_places=6, blank=True, null=True)  
    u_totalpayable = models.DecimalField(db_column='U_TotalPayable', max_digits=19, decimal_places=6, blank=True, null=True)  
    u_ewt2307 = models.DecimalField(db_column='U_EWT2307', max_digits=19, decimal_places=6, blank=True, null=True)  
    u_totalpayablerec = models.DecimalField(db_column='U_TotalPayableRec', max_digits=19, decimal_places=6, blank=True, null=True)  
    u_paymentvoucherno = models.CharField(db_column='U_PaymentVoucherNo', max_length=50, blank=True, null=True)  
    u_orrefno = models.CharField(db_column='U_ORRefNo', max_length=50, blank=True, null=True)  
    u_actualpaymentdate = models.DateTimeField(db_column='U_ActualPaymentDate', blank=True, null=True)  
    u_paymentreference = models.CharField(db_column='U_PaymentReference', max_length=100, blank=True, null=True)  
    u_paymentstatus = models.CharField(db_column='U_PaymentStatus', max_length=50, blank=True, null=True)  
    u_remarks = models.TextField(db_column='U_Remarks', blank=True, null=True)  
    u_updatedate = models.DateTimeField(db_column='U_UpdateDate', blank=True, null=True)  
    u_createdate = models.DateTimeField(db_column='U_CreateDate', blank=True, null=True)  
    u_podnum = models.CharField(db_column='U_PODNum', max_length=25, blank=True, null=True)  
    u_podsonum = models.CharField(db_column='U_PODSONum', max_length=25, blank=True, null=True)  
    u_docnum = models.CharField(db_column='U_DocNum', max_length=254, blank=True, null=True)  
    u_aging = models.DateTimeField(db_column='U_Aging', blank=True, null=True)  
    u_apinvlinenum = models.CharField(db_column='U_APInvLineNum', max_length=10, blank=True, null=True)  
    u_pvno = models.CharField(db_column='U_PVNo', max_length=50, blank=True, null=True)  
    u_tpincharge = models.CharField(db_column='U_TPincharge', max_length=50, blank=True, null=True)  
    u_caanddp = models.DecimalField(db_column='U_CAandDP', max_digits=19, decimal_places=6, blank=True, null=True)  
    u_interest = models.DecimalField(db_column='U_Interest', max_digits=19, decimal_places=6, blank=True, null=True)  
    u_otherdeductions = models.DecimalField(db_column='U_OtherDeductions', max_digits=19, decimal_places=6, blank=True, null=True)  
    u_totaldeductions = models.DecimalField(db_column='U_TOTALDEDUCTIONS', max_digits=19, decimal_places=6, blank=True, null=True)  
    u_remarks1 = models.CharField(db_column='U_REMARKS1', max_length=254, blank=True, null=True)  
    u_totalap = models.DecimalField(db_column='U_TotalAP', max_digits=19, decimal_places=6, blank=True, null=True)  
    u_vartp = models.DecimalField(db_column='U_VarTP', max_digits=19, decimal_places=6, blank=True, null=True)  

    class Meta:
        managed = False
        db_table = '@PCTP_TP'

################# PCTP PRICING
class PctpPricing(models.Model):
    code = models.AutoField(db_column='Code', primary_key=True)  
    name = models.CharField(db_column='Name', max_length=100, blank=True, null=True)  
    u_bookingid = models.CharField(db_column='U_BookingId', max_length=50, blank=True)  
    u_bookingdate = models.DateTimeField(db_column='U_BookingDate', blank=True, null=True)  
    u_customername = models.CharField(db_column='U_CustomerName', max_length=254, blank=True, null=True)  
    u_clienttag = models.CharField(db_column='U_ClientTag', max_length=100, blank=True, null=True)  
    u_clientproject = models.CharField(db_column='U_ClientProject', max_length=100, blank=True, null=True)  
    u_truckername = models.CharField(db_column='U_TruckerName', max_length=100, blank=True, null=True)  
    u_truckertag = models.CharField(db_column='U_TruckerTag', max_length=100, blank=True, null=True)  
    u_vehicletypecap = models.CharField(db_column='U_VehicleTypeCap', max_length=50, blank=True, null=True)  
    u_deliverystatus = models.CharField(db_column='U_DeliveryStatus', max_length=50, blank=True, null=True)  
    u_triptype = models.CharField(db_column='U_TripType', max_length=50, blank=True, null=True)  
    u_remarksdtr = models.TextField(db_column='U_RemarksDTR', blank=True, null=True)  
    u_remarkspod = models.TextField(db_column='U_RemarksPOD', blank=True, null=True)  
    u_grossclientrates = models.DecimalField(db_column='U_GrossClientRates', max_digits=19, decimal_places=6, blank=True, null=True)  
    u_grossclientratestax = models.DecimalField(db_column='U_GrossClientRatesTax', max_digits=19, decimal_places=6, blank=True, null=True)  
    u_ratebasis = models.CharField(db_column='U_RateBasis', max_length=50, blank=True, null=True)  
    u_taxtype = models.CharField(db_column='U_TaxType', max_length=50, blank=True, null=True)  
    u_grossprofitnet = models.DecimalField(db_column='U_GrossProfitNet', max_digits=19, decimal_places=6, blank=True, null=True)  
    u_totaladdtlcharges = models.DecimalField(db_column='U_TotalAddtlCharges', max_digits=19, decimal_places=6, blank=True, null=True)  
    u_totaladdtlcharges2 = models.DecimalField(db_column='U_totalAddtlCharges2', max_digits=19, decimal_places=6, blank=True, null=True)  
    u_addtlcharges = models.DecimalField(db_column='U_AddtlCharges', max_digits=19, decimal_places=6, blank=True, null=True)  
    u_grossprofit = models.DecimalField(db_column='U_GrossProfit', max_digits=19, decimal_places=6, blank=True, null=True)  
    u_totalinitialclient = models.DecimalField(db_column='U_TotalInitialClient', max_digits=19, decimal_places=6, blank=True, null=True)  
    u_totalinitialtruckers = models.DecimalField(db_column='U_TotalInitialTruckers', max_digits=19, decimal_places=6, blank=True, null=True)  
    u_totalgrossprofit = models.DecimalField(db_column='U_TotalGrossProfit', max_digits=19, decimal_places=6, blank=True, null=True)  
    u_clienttag2 = models.CharField(db_column='U_ClientTag2', max_length=100, blank=True, null=True)  
    u_updatedate = models.DateTimeField(db_column='U_UpdateDate', blank=True, null=True)  
    u_createdate = models.DateTimeField(db_column='U_CreateDate', blank=True, null=True)  
    u_podnum = models.CharField(db_column='U_PODNum', max_length=25, blank=True, null=True)  
    u_grosstruckerrates = models.DecimalField(db_column='U_GrossTruckerRates', max_digits=19, decimal_places=6, blank=True, null=True)  
    u_grosstruckerratestax = models.DecimalField(db_column='U_GrossTruckerRatesTax', max_digits=19, decimal_places=6, blank=True, null=True)  
    u_ratebasist = models.CharField(db_column='U_RateBasisT', max_length=50, blank=True, null=True)  
    u_taxtypet = models.CharField(db_column='U_TaxTypeT', max_length=50, blank=True, null=True)  
    u_demurrage4 = models.DecimalField(db_column='U_Demurrage4', max_digits=19, decimal_places=6, blank=True, null=True)  
    u_addtlcharges2 = models.DecimalField(db_column='U_AddtlCharges2', max_digits=19, decimal_places=6, blank=True, null=True)  
    u_grossprofitc = models.DecimalField(db_column='U_GrossProfitC', max_digits=19, decimal_places=6, blank=True, null=True)  
    u_addtldrop = models.DecimalField(db_column='U_AddtlDrop', max_digits=19, decimal_places=6, blank=True, null=True)  
    u_addtldrop2 = models.DecimalField(db_column='U_AddtlDrop2', max_digits=19, decimal_places=6, blank=True, null=True)  
    u_backload = models.DecimalField(db_column='U_Backload', max_digits=19, decimal_places=6, blank=True, null=True)  
    u_backload2 = models.DecimalField(db_column='U_Backload2', max_digits=19, decimal_places=6, blank=True, null=True)  
    u_boomtruck = models.DecimalField(db_column='U_BoomTruck', max_digits=19, decimal_places=6, blank=True, null=True)  
    u_boomtruck2 = models.DecimalField(db_column='U_BoomTruck2', max_digits=19, decimal_places=6, blank=True, null=True)  
    u_demurrage = models.DecimalField(db_column='U_Demurrage', max_digits=19, decimal_places=6, blank=True, null=True)  
    u_demurrage2 = models.DecimalField(db_column='U_Demurrage2', max_digits=19, decimal_places=6, blank=True, null=True)  
    u_demurrage3 = models.DecimalField(db_column='U_Demurrage3', max_digits=19, decimal_places=6, blank=True, null=True)  
    u_manpower = models.DecimalField(db_column='U_Manpower', max_digits=19, decimal_places=6, blank=True, null=True)  
    u_manpower2 = models.DecimalField(db_column='U_Manpower2', max_digits=19, decimal_places=6, blank=True, null=True)  
    u_noofdrops = models.DecimalField(db_column='U_NoOfDrops', max_digits=19, decimal_places=6, blank=True, null=True)  
    u_deliveryorigin = models.TextField(db_column='U_DeliveryOrigin', blank=True, null=True)  
    u_destination = models.TextField(db_column='U_Destination', blank=True, null=True)  

    class Meta:
        managed = False
        db_table = '@PCTP_Pricing'





        

